version: '3'
services:
    openclinic:
        image: plydot/openclinic:latest
        ports:
            - 5050:80
        depends_on:
            - openclinicdb
    openclinicdb:
        image: mysql:5.7
        ports:
            - 33067:3306
        environment:
            MYSQL_ROOT_PASSWORD: 0pen
            MYSQL_DATABASE: openclinic
            MYSQL_USER: openclinic
            MYSQL_PASSWORD: 0pen
        command: --skip-ssl --lower-case-table-names=1
